# Generated by Django 4.2.13 on 2024-06-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generoUsuario',
            fields=[
                ('id_genero', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usuarioAdopcion',
            fields=[
                ('uuid', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidoP', models.CharField(max_length=20)),
                ('apellidoM', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('profesion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=200)),
                ('direccion2', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('cod_postal', models.CharField(max_length=10)),
                ('observacion', models.CharField(max_length=350)),
                ('check_correos', models.BooleanField()),
                ('genero', models.ForeignKey(db_column='genero', on_delete=django.db.models.deletion.CASCADE, to='formularioApp.generousuario')),
            ],
        ),
    ]
